[package]
name = "sleigh-eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh-rs = { git = "https://github.com/rbran/sleigh-rs" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
